
[functions.create-payment-intent]
enabled = true
verify_jwt = false
import_map = "./functions/create-payment-intent/deno.json"
entrypoint = "./functions/create-payment-intent/index.ts"

[functions.send-notification]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-notification/index.ts"
